# Generated by Django 2.0.5 on 2018-05-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_polls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polls',
            name='question',
            field=models.IntegerField(),
        ),
    ]
