# Generated by Django 2.0.5 on 2018-05-17 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='routeMaster',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('rname', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='routeStop',
            fields=[
                ('rsid', models.AutoField(primary_key=True, serialize=False)),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busMaster.routeMaster')),
            ],
        ),
        migrations.CreateModel(
            name='stopMaster',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='routestop',
            name='stop_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busMaster.stopMaster'),
        ),
    ]
