# Generated by Django 2.0.5 on 2018-05-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busMaster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routestop',
            name='stopNum',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='routestop',
            unique_together={('stop_id', 'route_id', 'stopNum')},
        ),
    ]
