# Generated by Django 2.0.5 on 2018-05-25 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busMaster', '0002_auto_20180517_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='routemaster',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 5, 25, 9, 49, 1, 494677)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routemaster',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
