# Generated by Django 2.0.5 on 2018-05-25 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busMaster', '0003_auto_20180525_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='routestop',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 5, 25, 9, 58, 20, 620684)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routestop',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stopmaster',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 5, 25, 9, 58, 33, 738496)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stopmaster',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
